drop database cdpads on cluster aeon_cluster_two_shards_two_replicas;

create database cdpads on cluster aeon_cluster_4shards_1replicas;

truncate table cdpads.ads_csmr_tag_total_df on cluster aeon_cluster_4shards_1replicas;

select count(1) from cdpads.ads_csmr_tag_total_df_local

select * from system.tables where name like '%ads_csmr_tag_total_df%'

drop  TABLE cdpads.ads_csmr_tag_total_df_local on cluster aeon_cluster_4shards_1replicas ;
drop  TABLE cdpads.ads_csmr_tag_total_df on cluster aeon_cluster_4shards_1replicas ;

CREATE TABLE cdpads.ads_csmr_tag_total_df_local on cluster aeon_cluster_4shards_1replicas
(
    oneid                           String   comment 'oneid',
    mgbrand_id                      String    comment '业态/法人/门店id',
    age                             String            comment '年龄',
    gender                          String    comment '性别',
    constellation                   String    comment '星座',
    customerlifestyle               String    comment '生活方式',
    customer_life_cycle             String    comment '生命周期阶段',
    crm_membership_level            String    comment 'CRM会员等级',
    membership_level                String    comment '消费者价值等级',
    join_membership                 String    comment '是否会员',
    regist_date                     String    comment '会员注册日期',
    member_first_login_applet_date  String    comment '会员首登小程序日期',
    member_first_login_app_date     String    comment '会员首登APP日期',
    purchase_member                 String    comment '交易会员',
    active_firstbuy                 String    comment '活跃首购',
    active_secondbuy                String    comment '活跃复购',
    active_customer                 String    comment '活跃用户',
    normal_active_customer          String    comment '一般活跃用户',
    inactive_customer               String    comment '睡眠用户',
    churned_customer                String    comment '休眠用户（流失）',
    hsitory_member_poStrings           String         comment '会员历史积分',
    current_member_poStrings           String         comment '会员当前积分',
    member_poStrings_exchange_times    String         comment '积分兑换次数',
    digital_customer                String    comment '是否数字化会员',
    digital_time                    String    comment '数字化时间',
    is_share                        String    comment '是否分享赚用户',
    buy_count                       String         comment '消费频次',
    buy_count_level                 String    comment '消费频率',
    pay_amount_31days               decimal(16, 2) ,
    pay_amount_91days               decimal(16, 2) ,
    pay_amount_181days              decimal(16, 2) ,
    pay_amount_365days              decimal(16, 2) ,
    ordervaluelevel                 String    comment '客单价值等级',
    avg_order_value                 decimal(16, 2) ,
    avg_order_num                   decimal(16, 2)    ,
    ave_discount                    decimal(16, 2) ,
    avg_order_discount              String    comment '平均商品价格',
    avg_product_price               decimal(16, 2) ,
    brand_penetrance                String    comment '品牌渗透率',
    brand_penetrance_percentage     decimal(16, 2) ,
    category_penetrance             String           comment '品类渗透率',
    category_penetrance_percentage  decimal(16, 2) ,
    first_order_value               decimal(16, 2) ,
    first_order_time                String    comment '首次交易时间',
    first_order_num                 String         comment '首次交易件数',
    first_order_channel             String    comment '首次交易渠道',
    first_order_product             String           comment '首次交易商品',
    first_order_promotion           decimal(16, 2) ,
    last_order_value                decimal(16, 2) ,
    last_order_time                 String    comment '最近一次交易时间',
    last_order_num                  String         comment '最近一次交易件数',
    last_order_product              String           comment '最近一次交易商品',
    last_order_promotion            decimal(16, 2) ,
    last_order_channel              String    comment '最近一次交易渠道',
    store_first_buy_date            String    comment '门店首次消费时间',
    store_last_buy_date             String    comment '门店最近一次购买日期',
    store_csp_avg_num_31days        decimal(16, 2)    ,
    store_csp_avg_num_91days        decimal(16, 2)    ,
    store_csp_avg_num_181days       decimal(16, 2)    ,
    store_csp_avg_num_365days       decimal(16, 2)    ,
    store_csp_avg_value_31days      decimal(16, 2) ,
    store_csp_avg_value_91days      decimal(16, 2) ,
    store_csp_avg_value_181days     decimal(16, 2) ,
    store_csp_avg_value_365days     decimal(16, 2) ,
    online_first_buy_date           String    comment '线上首次消费时间',
    online_last_buy_date            String    comment '线上最近一次购买日期',
    online_csp_avg_num_31days       decimal(16, 2)    ,
    online_csp_avg_num_91days       decimal(16, 2)    ,
    online_csp_avg_num_181days      decimal(16, 2)    ,
    online_csp_avg_num_365days      decimal(16, 2)    ,
    online_consumption_avg_value    decimal(16, 2) ,
    frequent_time                   String   comment '高频-时间段',
    frequent_time_online            String   comment '高频时间段-线上',
    frequent_time_offline           String   comment '高频时间段-线下',
    frequent_weekday                String   comment '高频-日',
    frequent_weekday_online         String   comment '高频-日-线上',
    frequent_weekday_offline        String   comment '高频-日-线下',
    weekend_or_work                 String   comment '工作日/休息日偏好',
    weekend_or_tuesday              String   comment '周二/周末偏好',
    frequent_holiday                String   comment '高频-节假日',
    frequent_season                 String   comment '高频-季节',
    frequent_month                  String            comment '高频-月份',
    frequent_shopping_festival      String   comment '高频-购物节',
    frequent_Stringerval               String   comment '高概率消费区间',
    frequent_Stringerval_online        String   comment '高概率消费区间-线上',
    frequent_Stringerval_offline       String   comment '高概率消费区间-线下',
    avg_purchase_Stringerval           String            comment '平均消费周期',
    promotion_purchase_predict      String           comment '促销购买偏好',
    payment_preference              String           comment '支付方式偏好',
    preferred_brand                 String           comment '品牌偏好预测',
    preferred_category              String           comment '品类偏好预测',
    next_purchase_date              String    comment '下次购买时间预测',
    products_purchased              String     comment '已购商品',
    purchased_brand                 String           comment '已购品牌',
    purchased_category              String           comment '已购品类',
    proportion_of_ptl_products      String    comment '促销商品占比',
    payment_method                  String           comment '支付方式',
    overall_consumption_channel     String           comment '总体消费渠道',
    online_consumption              String           comment '线上消费渠道',
    offline_channel                 String           comment '线下消费渠道',
    membership_channel              String    comment '入会渠道',
    membership_store                String   comment '入会门店',
    province                        String   comment '活跃省份',
    province_online                 String   comment '活跃省份-线上',
    province_offline                String   comment '活跃省份-线下',
    city                            String   comment '活跃城市',
    city_online                     String   comment '活跃城市-线上',
    city_offline                    String   comment '活跃城市-线下',
    district                        String   comment '活跃区',
    main_store                      String   comment '主要消费门店',
    secondary_store                 String   comment '次要消费门店',
    used_coupon                     String         comment '已使用优惠券',
    available_coupon                String         comment '未使用优惠券',
    overdue_coupon                  String         comment '已过期优惠券',
    coupon_write_off_rate           decimal(16, 2) ,
    prp_of_new_product_purchase     decimal(16, 2) ,
    etl_time                        String    comment 'etl_time',
    crm_invaild_time                String    comment '会员等级失效时间',
    org_type                        String    comment '粒度编号',
    member_stage                    String    comment '会员状态：活跃用户/预警用户/流失用户',
    member_loyalty                  String    comment '会员忠诚度：高度忠诚/中度忠诚/低度忠诚',
    member_lifecycle_sage           String    comment '会员价值等级:重要价值/发展价值/维护价值/一般价值',
    predicted_high_value            String    comment '高价值新用户预测:是/否',
    marketing_sensitivity           String    comment '营销敏感度:敏感型/一般/麻木型',
    churn_rate                      String    comment '流失风险:低/1中/高',
    high_churn_possibility          String    comment '高风险流失用户:是/否',
    cumulative_number_sub_180days   String    comment '会员在180天内累计消费次数',
    rank_of_sumofconsumption_sup    String    comment '是否为一年内消费金额总额在前20%的会员',
    marketing_buy_conversion_count  String            comment '营销转化消费次数:用券订单数',
    marketing_conversion_value      decimal(18, 2) ,
    discount_value                  decimal(18, 2) ,
    cross_business                  String           comment '跨法人',
    cross_shop                      String           comment '跨门店',
    active_low_frequency            String    comment '活跃低频',
    promotion_content_predict       String           comment '促销内容偏好预测',
    marketing_category_predict      String           comment '活动类型偏好',
    activity_title                  String           comment '营销活动名称',
    activity_key_words              String           comment '营销活动关键词',
    marketing_transformation_number String         comment '营销转化参与次数',
    accept_market_sms               String    comment '是否接受营销短信通知',
    accept_sys_sms                  String    comment '是否接受系统短信通知',
    marketing_count                 String         comment '营销频次',
    marketing_channel_predict       String           comment '营销渠道偏好预测',
    membership_status               String    comment '会员状态',
    marketing_channel               String           comment '营销渠道',
    marketing_success_rate          decimal(18, 2) ,
    activtiy_participation_Stringerval decimal(18, 2) ,
    purchased_department            String   comment '已购Department名称',
    purchased_article               String           comment '已购article名称',
    purchased_section               String           comment '已购section名称',
    purchased_type                  String           comment '已购purchased_type名称',
    marketing_frequency             String         comment '营销互动活动总访问次数',
    activtiy_respone_Stringerval       decimal(18, 2) ,
    price_attention                 String    comment '会员价格关注度',
    mother_and_child                String    comment '母婴人群',
    sport_people                    String    comment '运动兴趣',
    food_people                     String    comment '美食兴趣',
    health_people                   String    comment '养生保健爱好者',
    birthday                        String    comment '生日',
    marketing_sensitive             String    comment '营销敏感度',
    created_on DateTime default now()


)   ENGINE = MergeTree()
PARTITION BY (mgbrand_id)
ORDER BY (mgbrand_id,oneid)
SETTINGS index_granularity = 8192;


drop table cdpads.ads_csmr_tag_total_df on cluster aeon_cluster_4shards_1replicas

--创建分布式表
create table if not exists cdpads.ads_csmr_tag_total_df on cluster aeon_cluster_4shards_1replicas as cdpads.ads_csmr_tag_total_df_local
engine=Distributed(aeon_cluster_4shards_1replicas,cdpads, ads_csmr_tag_total_df_local,sipHash64(oneid,mgbrand_id));